### ISSUE TITLE
/training以下URL限定 UIコンポーネント基盤実装仕様書（修正版）

### ISSUE THREAD

**Issue by kaikunnnn** [kaikunnnn/bono-training#12]
# /training以下URL限定 UIコンポーネント基盤実装仕様書（修正版）

## 概要
`/training` 以下のURL専用のUIコンポーネント基盤を構築する。既存の通常ページ（`Layout`）には影響を与えず、`TrainingLayout`使用ページのみに適用される独立したデザインシステムを実装する。

**重要**: 既存のTrainingコンポーネントには手を付けず、新しい基盤のみを構築する。

## 実装範囲
- 対象URL: `/training`、`/training/*` の全てのページ
- 対象コンポーネント: `TrainingLayout`を使用するページ内のみ
- 非対象: 通常の`Layout`を使用するページ（既存実装を維持）
- **除外**: 既存のTrainingコンポーネント（`TrainingCard.tsx`、`TrainingHero.tsx`等）

---

### 1.1 基本コンポーネントの導入
以下のShadcn/uiコンポーネントを導入し、Training専用にカスタマイズする：

```bash
# 導入するコンポーネント
npx shadcn-ui@latest add button
npx shadcn-ui@latest add input  
npx shadcn-ui@latest add card
npx shadcn-ui@latest add badge
npx shadcn-ui@latest add form
npx shadcn-ui@latest add select
npx shadcn-ui@latest add checkbox
```

### 1.2 Training専用コンポーネントディレクトリ作成

```
src/components/training/ui/
├── button.tsx          # Training専用Button
├── input.tsx           # Training専用Input
├── card.tsx            # Training専用Card
├── badge.tsx           # Training専用Badge
├── form.tsx            # Training専用Form
├── select.tsx          # Training専用Select
└── checkbox.tsx        # Training専用Checkbox
```

**要件:**
- Shadcn/uiの元コンポーネントをコピーして`src/components/training/ui/`に配置
- Training専用のクラス名とスタイリングを適用
- 既存の`@/components/ui/`には影響しない
- **既存のTrainingコンポーネントは一切変更しない**

---

### 2.1 CSS変数の定義

`src/styles/training.css`を新規作成し、以下の変数を定義：

```css
/* Training専用CSS変数 */
:root {
  /* Colors */
  --training-primary: 29 56 47;           /* #1D382F */
  --training-primary-foreground: 248 249 245; /* #F8F9F5 */
  --training-secondary: 248 249 245;      /* #F8F9F5 */
  --training-secondary-foreground: 29 56 47;
  --training-background: 248 249 245;     /* #F8F9F5 */
  --training-card: 255 255 255;          /* #FFFFFF */
  --training-border: 229 231 235;        /* #E5E7EB */
  --training-accent: 255 153 0;          /* #FF9900 */
  
  /* Typography */
  --training-font-primary: 'Rounded Mplus 1c', sans-serif;
  --training-font-secondary: 'Inter', sans-serif;
  --training-font-mono: 'Futura', monospace;
  
  /* Spacing (8px grid) */
  --training-space-1: 0.25rem;   /* 4px */
  --training-space-2: 0.5rem;    /* 8px */
  --training-space-3: 0.75rem;   /* 12px */
  --training-space-4: 1rem;      /* 16px */
  --training-space-6: 1.5rem;    /* 24px */
  --training-space-8: 2rem;      /* 32px */
  --training-space-12: 3rem;     /* 48px */
  --training-space-16: 4rem;     /* 64px */
  
  /* Component Sizes */
  --training-button-sm: 2rem;     /* 32px */
  --training-button-md: 2.5rem;   /* 40px */
  --training-button-lg: 3rem;     /* 48px */
  --training-input-height: 2.75rem; /* 44px */
  --training-border-radius: 0.5rem; /* 8px */
}
```

### 2.2 Tailwind設定の拡張

`tailwind.config.ts`に以下を追加：

```javascript
extend: {
  colors: {
    'training': {
      'primary': 'hsl(var(--training-primary))',
      'primary-foreground': 'hsl(var(--training-primary-foreground))',
      'secondary': 'hsl(var(--training-secondary))',
      'secondary-foreground': 'hsl(var(--training-secondary-foreground))',
      'background': 'hsl(var(--training-background))',
      'card': 'hsl(var(--training-card))',
      'border': 'hsl(var(--training-border))',
      'accent': 'hsl(var(--training-accent))',
    }
  },
  fontFamily: {
    'training-primary': ['var(--training-font-primary)'],
    'training-secondary': ['var(--training-font-secondary)'],
    'training-mono': ['var(--training-font-mono)'],
  },
  spacing: {
    'training-1': 'var(--training-space-1)',
    'training-2': 'var(--training-space-2)',
    'training-3': 'var(--training-space-3)',
    'training-4': 'var(--training-space-4)',
    'training-6': 'var(--training-space-6)',
    'training-8': 'var(--training-space-8)',
    'training-12': 'var(--training-space-12)',
    'training-16': 'var(--training-space-16)',
  }
}
```

---

### 3.1 Training専用Buttonコンポーネント

`src/components/training/ui/button.tsx`:

```typescript
interface TrainingButtonProps {
  variant?: 'default' | 'secondary' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
  className?: string;
  onClick?: () => void;
  disabled?: boolean;
}
```

**スタイル仕様:**
- Primary: `bg-training-primary text-training-primary-foreground`
- Secondary: `bg-training-secondary text-training-secondary-foreground`
- フォント: `font-training-primary`
- 角丸: `rounded-full` (Training特有のデザイン)

### 3.2 Training専用Cardコンポーネント

```typescript
interface TrainingCardProps {
  children: React.ReactNode;
  className?: string;
  variant?: 'default' | 'elevated';
}
```

**スタイル仕様:**
- 背景: `bg-training-card`
- 境界線: `border-training-border`
- 影: `shadow-training-card`

### 3.3 Training専用Badgeコンポーネント

```typescript
interface TrainingBadgeProps {
  children: React.ReactNode;
  variant?: 'default' | 'accent' | 'outline';
  size?: 'sm' | 'md';
}
```

---

### 4.1 テストページの作成
`src/pages/Training/UITest.tsx`を作成し、新しいコンポーネントの動作確認を行う：

```typescript
// 新しいTraining UIコンポーネントの表示確認用
import { Button } from '@/components/training/ui/button';
import { Card } from '@/components/training/ui/card';
import { Badge } from '@/components/training/ui/badge';
```

### 4.2 ルート追加
`App.tsx`に`/training/ui-test`ルートを追加し、新しいコンポーネントの動作確認を可能にする

---

### インポート仕様
```typescript
// Training専用コンポーネントの使用
import { Button } from '@/components/training/ui/button';
import { Card } from '@/components/training/ui/card';

// 通常ページでは既存を維持
import { Button } from '@/components/ui/button';
```

### CSSの読み込み
`TrainingLayout.tsx`で Training専用CSSを読み込み：

```typescript
import '@/styles/training.css';
```

### 型定義
`src/types/training-ui.ts`を作成し、Training専用UIの型を定義

---

## 完成条件

1. ✅ Phase1のShadcn/uiコンポーネントが全て導入済み
2. ✅ Training専用CSS変数が定義済み
3. ✅ Tailwind設定にTraining専用クラスが追加済み
4. ✅ `/training/ui-test`ページで新しいButtonコンポーネントが正常表示
5. ✅ 既存の通常ページ（`Layout`使用）に影響なし
6. ✅ **既存のTrainingコンポーネントに一切変更なし**

## 注意事項

- **既存コンポーネント保護**: 現在の`TrainingCard`、`TrainingHero`等には一切手を付けない
- **独立した基盤**: 新しいUIシステムは完全に独立して動作
- **命名規則**: Training専用コンポーネントには明確にプレフィックス・ディレクトリで区別
- **パフォーマンス**: 通常ページには不要なTraining用CSSを読み込まない
- **段階的実装**: 動作確認しながら進める

この仕様で実装を開始してください。既存のTrainingコンポーネントは一切変更せず、新しい基盤のみを構築します。
